name: Publish extension

on:
  push:
    paths:
      - '.changeset/**'
      - 'extension/**'
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

      - name: Build extension
        run: pnpm extension:build

      - name: Publish extension
        working-directory: ./extension/vscode
        run: pnpm vsce publish --no-dependencies -p ${{secrets.VSCE_TOKEN}}
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
